# General Settings
name: Bigshane
job_title: NLP Engineer
email: bigshane319@gmail.com
description: I'm now finding ways to alleviate engineers' discomfort at Samsung. A variety of approaches and performance enhancements are available in DL models, currently the BERT variants.
avatar: /assets/img/profile/bertticon_hd.jpg # https://s3.amazonaws.com/uifaces/faces/twitter/dancounsell/128.jpg
favicon: /favicon.ico
twitter_handler: your_handler
analytics_code: UA-XXXXXXX-2
disqus: your_disqus_site

# Social Accounts
social_networks:
-  { name: facebook, url: '' }
-  { name: twitter, url: '' }
-  { name: instagram, url: '' }
-  { name: google-plus, url: '' }
-  { name: linkedin, url: 'http://www.linkedin.com/in/hodong-lee-ba2274112/' }
-  { name: skype, url: '' }
-  { name: github, url: '' }
-  { name: codepen, url: '' }
-  { name: stack-overflow, url: '' }
-  { name: dribbble, url: '' }
-  { name: behance, url: '' }
-  { name: pinterest, url: '' }
-  { name: tumblr, url: '' }
-  { name: youtube, url: '' }
-  { name: vimeo, url: '' }
-  { name: vine, url: '' }
-  { name: 500px, url: '' }
-  { name: flickr, url: '' }
-  { name: spotify, url: '' }
-  { name: steam, url: '' }
-  { name: wordpress, url: '' }
-  { name: xing, url: '' }
-  { name: bitcoin, url: '' }
-  { name: pocket, url: '' }
-  { name: applemusic, url: '' }

# Modules Settings
show_categories: 1
show_tags: 1
show_email: 1
show_rss: 0
show_comments: 1
show_menu: 1
fixed_sidebar: 1

# Defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      comments: "true"

# Serving
url: "https://bigshanedogg.github.io"
baseurl: "/home"

# Includes
include: ["_pages"]

# Outputting
permalink: /:categories/:title.html
category_dir: categories

# Pagination
paginate: 10
paginate_path: "/page:num/"

# Conversion
markdown: kramdown
excerpt_separator: <!--more-->
language_separator: <!--language-->

# Assets Settings
sass:
  sass_dir: assets/partials
  style: compressed

